name: .NET
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x      # <-- sin cache

      - name: Restore
        run: dotnet restore UIABank.sln

      - name: Build
        run: dotnet build UIABank.sln -c Release --no-restore

      # - name: Test
      #   run: dotnet test UIABank.sln -c Release --no-build --verbosity normal
